project:
  type: website
  output-dir: docs

website:
  title: "Olito's plots"
  sidebar:
    style: docked  
    contents:
      - section: "Secciones"     
      - href: index.qmd
        text: "Inicio"
      - href: donut.qmd
        text: "Donut chart"
      - href: contact.qmd
        text: "Contacto"

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "Contenido"
    css: styles.css

editor: visual

